services:
  shell:
    image: mfe-shell
    build:
      context: .
      dockerfile: projects/shell/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "4200:80"
    depends_on:
      - mfe-clients
      - mfe-login
      - mfe-user-clients
      - mfe-ds
    networks:
      - mfe-network

  mfe-clients:
    image: mfe-clients
    build:
      context: .
      dockerfile: projects/mfe-clients/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "4203:80"
    networks:
      - mfe-network

  mfe-login:
    image: mfe-login
    build:
      context: .
      dockerfile: projects/mfe-login/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "4202:80"
    networks:
      - mfe-network

  mfe-user-clients:
    image: mfe-user-clients
    build:
      context: .
      dockerfile: projects/mfe-user-clients/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "4204:80"
    networks:
      - mfe-network

  mfe-ds:
    image: mfe-ds
    build:
      context: .
      dockerfile: projects/mfe-ds/Dockerfile
    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "4201:80"
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
